HerokuでのTTS機能の追加
sizumita/MiniMaid pull request #26
Opened 2021-04-17 12:42 UTC by Shirataki2

## 機能追加

- [x] ボタン一つでHerokuにデプロイする(TTS機能付き)

### 備考

- jtalkdllのビルド関係でエラーが発生していたのでDockerfileのdtalkdllをフォークしたものに変えています．
- README.mdを改訂しました

2021-04-17 12:50 UTC, sizumita commented
気になったんですが、これdocker-composeを使用した際は大丈夫なんですかね？ 
herokuだけ別のDockerfileを用意したりとかしなくても

2021-04-17 12:56 UTC, Shirataki2 commented
docker-composeで動かしていないですので分からないですね．．．
(動かせるかどうかも検証してないです🙇)

Dockerfile自体は`COPY heroku_entrypoint.sh /bot`だけ追加していただければ現状動きます．

あとはHerokuではentrypointなどをheroku.ymlに書く仕様っぽいですので，compose使わずとも色々融通が利くのかなあと．

2021-04-17 14:01 UTC, sizumita commented
了解です、試してみます〜

2021-04-18 01:27 UTC, sizumita requested changes

2021-04-18 01:27 UTC, sizumita commented on heroku.yml
> +    bot: Dockerfile
ここを`bot: docker/heroku/Dockerfile`とかにできますか？

2021-04-18 03:07 UTC, sizumita commented
これあれですね、jtalkdllのShiratakiさんの方のやつを手元でビルドしてみたんですが通ったので、jtalkdllの変更をPRとしてだしてもらえたりしますか？そうすれば最適化とか簡単にいけると思うので（現時点でもかなりビルド時間が違うので）

2021-04-18 03:07 UTC, sizumita commented
> jtalkdllの変更をPRとしてだしてもらえたりしますか
これ僕でもできそうなのでやっちゃいますね

2021-04-18 03:38 UTC, sizumita commented
マージしたのでjtalkdllのパスも僕の方に変えちゃっていいかなと

2021-04-19 04:26 UTC, sizumita approved these changes

2021-04-19 04:26 UTC, merged

2021-04-19 04:31 UTC, sizumita commented
パス変えるの特に重要でもないので後でやっときますね〜。